[package]
name = "wx"
version = "0.1.25"
authors = ["Rob Hurkes <rhurkes@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.0"
chrono = "0.4"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slog = "2.4"
slog-async = "2.3"
slog-term = "2.4"
zmq = "0.9"
